## Support Vector Machine

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC

In [3]:
from sklearn import svm, datasets
dataset = datasets.load_iris()

In [4]:
model = svm.SVC(kernel ='linear',C=1.00)
model.fit(dataset.data, dataset.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

## Accuracy of model

In [5]:
model.score(dataset.data, dataset.target)

0.9933333333333333

### make prediction

In [6]:
expected = dataset.target
predicted = model.predict(dataset.data)
predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Summarize the fit of the model & Confusion matrics

In [7]:
from sklearn import metrics
#from sklearn.metrics import confusion_matrix
#from sklearn.metrics import classification_report
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      0.98      0.99        50
           2       0.98      1.00      0.99        50

    accuracy                           0.99       150
   macro avg       0.99      0.99      0.99       150
weighted avg       0.99      0.99      0.99       150

[[50  0  0]
 [ 0 49  1]
 [ 0  0 50]]


## Tunning parameter

In [8]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

iris = datasets.load_iris()

In [9]:
x = iris.data[:,:2] # we only take the first two features.
y = iris.target

In [10]:
def MySVMClassifier( my_kernel, my_C, my_gamma):
    
    svc = svm.SVC(kernel=my_kernel, C=my_C, gamma=my_gamma)
    svc.fit(x,y)
    print(svc.score(x,y))
    h=0.02
    x_min, x_max = x[:,0].min() -1, x[:,0].max() +1
    y_min, y_max = x[:,1].min() -1, x[:,1].max() +1
    
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    
    plt.subplot(1,1,1)
    Z = svc.predict(np.c_[xx.ravel(),yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, cmap=plt.cm.Paired, alpha=0.8)
    plt.scatter(x[:,0],x[:,1], c=y)
    plt.xlabel(" Sepal lenght")
    plt.ylabel(" sepal width")
    plt.xlim(xx.min(), xx.max())
    plt.show()

In [11]:
from ipywidgets import widgets
from IPython.html.widgets import interact

import warnings
warnings.filterwarnings('ignore')

In [12]:
i = interact(MySVMClassifier, my_kernel=({'linear','rbf'}),my_C=(0.1,40),my_gamma=(0.11,40))

interactive(children=(Dropdown(description='my_kernel', options=('linear', 'rbf'), value='linear'), FloatSlide…